name: Tests 

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Tests check
      run: docker-compose run backend_sector bash -c  "yarn && yarn jest --coverage --forceExit"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}